parameters:
    cron.resolver.class:        Cron\CronBundle\Cron\Resolver
    cron.manager.class:         Cron\CronBundle\Cron\Manager
    cron.command_builder.class: Cron\CronBundle\Cron\CommandBuilder
    cron.executor.class:        Cron\Executor\Executor
    cron.validator.class:       Cron\Validator\CrontabValidator

services:
    Cron\CronBundle\Command\CronCommand:
        arguments: ['@cron.command_builder']
        tags: [console.command]

    Cron\CronBundle\Command\CronRunCommand:
        tags: [console.command]

    Cron\CronBundle\Command\CronCreateCommand:
        tags: [console.command]

    Cron\CronBundle\Command\CronDeleteCommand:
        tags: [console.command]

    Cron\CronBundle\Command\CronDisableCommand:
        tags: [console.command]

    Cron\CronBundle\Command\CronEnableCommand:
        tags: [console.command]

    Cron\CronBundle\Command\CronListCommand:
        tags: [console.command]

    Cron\CronBundle\Command\CronStartCommand:
        tags: [console.command]

    Cron\CronBundle\Command\CronStopCommand:
        tags: [console.command]

    cron.resolver:
        class: "%cron.resolver.class%"
        arguments: ["@cron.manager", "@cron.command_builder", "%kernel.root_dir%"]
        public: true
    cron.manager:
        class: "%cron.manager.class%"
        arguments: ["@doctrine"]
        public: true
    cron.executor:
        class: "%cron.executor.class%"
        public: true
    cron.command_builder:
        class: "%cron.command_builder.class%"
        arguments: ["%kernel.environment%"]
    cron.validator:
        class: "%cron.validator.class%"
        public: true